### ISSUE TITLE
What am i supposed to put in the TAG field?

### ISSUE THREAD

**Issue by VingGit** [cerus/jda-slash-commands#1]
i just can't seem to get this to work with maven

**Comment by cerus** [comment]
The latest version is `1.0.1`. You can see all available versions [here](https://jitpack.io/#cerus/jda-slash-commands).

**Comment by VingGit** [comment]
Oh my that was fast, thank you!28.3.2021 19.51 Maximilian Dorn ***@***.***> kirjoitti:
The latest version is 1.0.1. You can see all available versions here.
