### ISSUE TITLE
Discord components

### ISSUE THREAD

**Issue by PringlePot** [cerus/jda-slash-commands#14]
It would be cool to have the discord components integrated in here. https://discord.com/developers/docs/interactions/message-components I think this is the best project for it, due to it also being with interactions

**Comment by cerus** [comment]
Oh, I've never heard of them, that's pretty cool. JDA has implemented those already in their development branch though, so as soon as they release 4.3.0 this project becomes pretty much obsolete. I'm not sure if it's worth the time and effort, but if someone wants to implement that, that's fine with me

**Comment by cerus** [comment]
Alright, its the weekend and I have nothing to do, so I'll probably implement those components today.

**Comment by PringlePot** [comment]
pog

**Comment by cerus** [comment]
Components are now available in 1.3.0, check the examples in the README to see how to use them

**Comment by PringlePot** [comment]
Such a shame, JDA releases it the same day 💀

**Comment by cerus** [comment]
I don't see a new release

**Comment by PringlePot** [comment]
they pushed it to main branch I think, the other things for 4.3 arent done
yet. So that will probably take some time.

Op zo 6 jun. 2021 om 14:43 schreef Maximilian Dorn ***@***.***

**Comment by cerus** [comment]
Alright, thanks for the info ^^
