### ISSUE TITLE
Where is the jda parameter coming from?

### ISSUE THREAD

**Issue by VingGit** [cerus/jda-slash-commands#2]
In your example, you have the following line:

`JDASlashCommands.initialize(jda, BOT_TOKEN, APPLICATION_ID);`

What is that jda argument?

**Comment by cerus** [comment]
That's your JDA instance. See https://github.com/DV8FromTheWorld/JDA#creating-the-jda-object

**Comment by VingGit** [comment]
oh, i'm a bit slow today. thanks. just a sec, i'll prolly be back in a moment.

**Comment by VingGit** [comment]
trying to get this to work, is your example supposed to be on the same class with JDA object or with one of the event listeners?

i'm trying to get this to list all available commanda so i guess it should be in the same class where the jda object is created?

**Comment by cerus** [comment]
It doesn't really matter in which class you put it as long as you have a JDA instance available. You could initialize (`JDASlashCommands.initialize(jda, BOT_TOKEN, APPLICATION_ID);`) the slash commands right after you've created your JDA instance.

```java
public class Launcher {
    private static final String BOT_TOKEN = "********";
    private static final String APPLICATION_ID = "12345654321";

    public static void main(String[] args) {
        JDA jda = JDABuilder.createDefault(BOT_TOKEN).build();
        JDASlashCommands.initialize(jda, BOT_TOKEN, APPLICATION_ID);
        // Register commands here
    }
}
```

**Comment by VingGit** [comment]
yeah, i almost got it. 

except now it's throwing an error like this:
`java.lang.IllegalStateException: Slash commands will not work without raw events! See JDABuilder#setRawEventsEnabled()`

**Comment by cerus** [comment]
You need to enable raw events in your JDA builder. `JDABuilder.createDefault(BOT_TOKEN).setRawEventsEnabled().build()`

**Comment by VingGit** [comment]
yeah, got it after a bit of googling. but oh boy we got another one. but this time it isn't caused by your bot. but my gui. i'm afraid you can't help me anymore but thank you for all the help regarding this plugin! you are very quick to answer.

**Comment by cerus** [comment]
No problem, feel free to open another issue if you encounter any other problems. I'll close this one.
