### ISSUE TITLE
after creating an entirely new bot, the commands won't initialize.

### ISSUE THREAD

**Issue by VingGit** [cerus/jda-slash-commands#5]
During testing, i deleted a current bot i had and made a new. This time, it goes into the initcommands method, executes it without exceptions. but the commands are not there.
![image](https://user-images.githubusercontent.com/61470249/116334747-64c2d300-a7de-11eb-996e-b19d3f666019.png)

![image](https://user-images.githubusercontent.com/61470249/116334440-e5350400-a7dd-11eb-89a2-34eb890fe3ff.png)

here's the pastebin, notice how in lines 76 and 176 it says if the initialization was successful

https://pastebin.com/p5gGCpdq

here's the relevant github again,if it's of any help. https://github.com/VingGit/UnicaBot/blob/supermoniveto/src/main/java/Botti/Botti.java

**Comment by VingGit** [comment]
huh, i'm missing something crucial here. I changed the contents  of the method back to that provided template and it still acts all the same. Enters the method correctyl but nothing happens.

**Comment by cerus** [comment]
Currently at work, I'll get back to you

**Comment by cerus** [comment]
You said you made a new bot, did you change the value of your APPLICATION_ID variable to the new application id?

**Comment by VingGit** [comment]
indeed i did. That makes it so weird.

First i got it from a config file and then i changed it to hardcoded and still the result is the same.

**Comment by cerus** [comment]
`submitGuildCommand()` returns you a CompletableFuture, you can listen to the result by calling `whenComplete()`. Is the returned Throwable object null?

**Comment by VingGit** [comment]
ah, i'm sorry. i don't know how to proceed.

**Comment by cerus** [comment]
```java
submitGuildCommand(...).whenComplete((commandId, throwable) -> {
    System.out.println("COMMAND ID: " + commandId);
    if (throwable != null) {
        System.err.println(throwable.getMessage());
    }
});
```
Replace the `...` with your command and your command listener and let me know what it prints to the console

**Comment by VingGit** [comment]
it says 

`28.04 15:49:34 [Bot] de.cerus.jdasc.http.DiscordApiException: Expected one of [200, 201] but got 403`

and that's all

**Comment by cerus** [comment]
That means that the bot is not authorized to register a command. Are you sure that the bot token and the application id are both correct?

**Comment by VingGit** [comment]
they have to be, i got the from the very same page.

**Comment by VingGit** [comment]
i'll get back to you when i can

**Comment by PringlePot** [comment]
Did you give the bot command perms when adding it to the server?

**Comment by PringlePot** [comment]
using oauth

**Comment by VingGit** [comment]
What perms? I think i gave it the same perms as i did to the previous bot. I have been a bit busy these last days but i will check in 3 hours or so once i finally get back to the computer.

**Comment by cerus** [comment]
> Did you give the bot command perms when adding it to the server?

You're right, I completely forgot about that. Bots also need the slash commands permission.

![image](https://user-images.githubusercontent.com/46848982/116813057-30d70d00-ab52-11eb-9431-c44d4d2572f1.png)

**Comment by VingGit** [comment]
nah, i even tried to give it all the possible permissions and i got no luck. And yes, i did invite the bot again and i did restart it. The error is still the same. (and yes, i changed the application id.)

**Comment by PringlePot** [comment]
In the oAuth url generator you need to also select the following.

![image](https://user-images.githubusercontent.com/80323633/116818363-3ee55780-ab6b-11eb-99fe-6123fb1c64d6.png)

This is also shown in the discord api docs: https://discord.com/developers/docs/interactions/slash-commands

![image](https://user-images.githubusercontent.com/80323633/116818395-5de3e980-ab6b-11eb-987a-a9bb9203b2c6.png)

**Comment by VingGit** [comment]
You are a beautiful human being, you know that right? Thank you!

**Comment by PringlePot** [comment]
😃
