### ISSUE TITLE
Feature request: Easier listening to unregistered slash commands

### ISSUE THREAD

**Issue by PringlePot** [cerus/jda-slash-commands#8]
This lib creates the commands on every join, what causes you to get ratelimited quickly. A possible fix is getting the global commands / guild commands, and only updating when needed. 😄

**Comment by cerus** [comment]
The lib attempts to create the commands everytime the submitCommand method is called. It should be the users responsibility to check for any ratelimit issues.

**Comment by PringlePot** [comment]
I have been ratelimit due to my debugging amount, it is hard to listen to slash commands without registering them. Maybe just a seperate listener for that?

**Comment by PringlePot** [comment]
Like JDA

**Comment by PringlePot** [comment]
nvm it is possible

**Comment by PringlePot** [comment]
add like getArguments to the CommandInteractionEvent

**Comment by PringlePot** [comment]
so you can listen to that with JDA, and don't need to unregister all the commands :D

**Comment by cerus** [comment]
The CommandInteractionEvent is basically just a notification that an interaction just happened. Adding a new event that contains parsed arguments and everything shouldn't be too much of an issue

**Comment by PringlePot** [comment]
I've implemented checking if commands are equal
